
name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


   
jobs:
  build:
    runs-on: [windows-2019]
    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: build
        run: |
             msbuild Master_Audio_Terminal.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
      - name: publish
        run: |
             msbuild Master_Audio_Terminal.sln /t:Publish /p:Configuration=Release /p:Platform="Any CPU" /p:PublishDir="./artifacts"
      
