
name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


   
jobs:
  build:
    runs-on: [windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: build
        run: |
             msbuild Master_Audio_Terminal.sln /t:Build /p:Configuration=Release /p:Platform="Any CPU" /verbosity:minimal
      - name: publish
        run: |
             msbuild Master_Audio_Terminal.sln /t:Publish /p:Configuration=Release /p:Platform="Any CPU" /p:PublishDir="./artifacts"
             
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: WinForms-Package
          path: D:\a\Master_Audio_Terminal\Master_Audio_Terminal\artifacts\
